version: '3.8'

services:
  mural-cumple-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mural-cumple-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Persistencia de la base de datos SQLite
      - ./data/db:/app/db
      # Persistencia de archivos subidos
      - ./data/uploads:/app/uploads
    networks:
      - caddy_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  caddy_network:
    external: true 